#undef TAPPING_TERM
#define TAPPING_TERM 300

#define QUICK_TAP_TERM 0

#define COMBO_TERM 30

#define USB_SUSPEND_WAKEUP_DELAY 20
#define CAPS_LOCK_STATUS
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "e5bdm/XbJ0dB"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 2

#define RGB_MATRIX_STARTUP_SPD 60

